config/routes.rb
Broker::Application.routes.draw do
require 'sidekiq/web'
authenticate :user, lambda { |u| u.admin? } do
  mount Sidekiq::Web => '/sidekiq'
end

  resources :cloud_servers do
    resources :images
  end

  get "administration/list_users"
  get "administration/list_groups"
  get "administration/users_from_group"
  put "administration/toggle_approved_user"
  get 'administration/edit_user/:id', to: 'administration#edit_user', as: 'administration_edit_user'
  put 'administration/update_user/:id', to: 'administration#update_user', as: 'administration_update_user'
  delete "administration/delete_user"
  get 'administration/upload_csv'
  post 'administration/check_file'
  get 'administration/create_users'

  post 'machines/create/:id', to: 'machines#create', as: 'create_machine'
  get 'machines/:id', to: 'machines#show', as: 'machine'
  get 'machines', to: 'machines#index', as: 'machines'
  delete 'machines/:id', to: 'machines#destroy', as: 'destroy_machine'
  get 'machines/reboot/:id', to: 'machines#reboot', as: 'reboot_machine'

  resources :roles

  devise_for :users
  get "welcome/index"

  root 'welcome#index'

end

app/controllers/administration_controller.rb
require 'csv'
require 'set'
require 'fileutils'

class AdministrationController < ApplicationController

  def list_users
    authorize self
    #@users = User.all
    @q = User.search(params[:q])
    @users = @q.result(distinct: true).page params[:page]
  end

 def toggle_approved_user 
    authorize self
    @user = User.find(params[:id])
    @user.toggle_approved!
    if @user.save
      redirect_to administration_list_users_path
    else
      redirect_to administration_list_users_path, alert: "Error updating approvation"
    end
  end

  def delete_user 
    @user = User.find(params[:id])
    authorize @user
    @user.destroy
    redirect_to administration_list_users_path
  end

  def list_groups
    authorize self
    #@groups = Role.all
    @q = Role.search(params[:q])
    @groups = @q.result(distinct: true).page params[:page]
  end

  def users_from_group
   authorize self
   @role = Role.find(params[:id])
   @users = @role.users
  end

  def edit_user
    authorize self
    @user = User.find(params[:id])  
  end

  def update_user
    authorize self
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to administration_list_users_path
    else
      redirect_to administration_list_users_path, alert: "Error updating user"
    end
  end

  def upload_csv
    authorize self
    
  end

  def check_file
    # We check the file:
    #  * CSV file structure.
    #  * The users in the file MUST NOT exist.
    #  * The users MUST NOT be repeated in the file.
    #  * The role field format MUST BE correct.
    #  * The roles MUST exist.

    authorize self

    if not params[:upload]

      redirect_to administration_upload_csv_path, alert: "No file provided, upload a right file!!"
      return
    end

    @CSV_errors = Array.new
    @data_errors = Array.new
    @role_errors = Array.new
    my_file = params[:upload]
    @users = Set.new
    line_number = 1
    @users_to_create = 0
    @file_is_correct = false
    CSV.open(my_file.path) do |output|
      loop do
        begin
          break unless row = output.shift
          error = false
          email = row[0]
          user = User.find_by(email: email)
          if user != nil
            @data_errors << "line #{line_number}: the mail #{email} already exists"
            error = true
          end
          if @users.include?(email)
            @data_errors << "line #{line_number}: the mail #{email} is repeated"
            error = true
          else
            @users << email
          end
          roles = row[3].split(",")
          roles.each do |r|
            role = Role.find_by(name: r) 
            if role == nil
              @role_errors << "line #{line_number}: the role #{r} doesn't exist"
              error = true
            end
          end
          line_number += 1
          if not error
            @users_to_create += 1
          end
        rescue CSV::MalformedCSVError => e
          @CSV_errors << "CSV error in line #{line_number}"
          line_number += 1
        end
      end   
    end

    if @CSV_errors.empty? and @data_errors.empty? and @role_errors.empty?
      @file_is_correct = true
      path = "#{Rails.root}/tmp/" + (0...8).map { (65 + rand(26)).chr }.join
      FileUtils.cp(my_file.path, path)
      session[:my_file] = path
    end
  end

  def create_users
    authorize self
    @my_file = session[:my_file]
    if @my_file == nil
      redirect_to administration_upload_csv_path, alert: "You must provide a CSV file"
      return
    end
    session[:my_file] = nil
    @users_created = 0
    line_number = 1
    begin
      User.transaction do
        CSV.open(@my_file) do |output|
          loop do
            begin
              break unless row = output.shift
              user = User.new
              user.email = row[0]
              user.last_name = row[1]
              user.first_name = row[2]
              roles = row[3].split(',')
              roles.each do |r|
                role_to_find = Role.find_by(name: r)
                user.roles << role_to_find
              end
              temp_password = (0...8).map { (65 + rand(26)).chr }.join
              user.password = temp_password
              user.password_confirmation = temp_password
              line_number += 1    
              #user.confirm!
              user.confirmed_at = Time.now
              user.approved = true
              user.save
              @users_created += 1
            rescue CSV::MalformedCSVError => e
              # This will never happen
              @CSV_errors << "CSV error in line #{line_number}"
              line_number += 1
              raise
            end
          end
        end
      end
    rescue
      @error = "Transaction aborted"
    end
    FileUtils.remove_file(@my_file)
    flash[:notice] = "#{@users_created} #{'user'.pluralize(@users_created)} created"
  end

  private
    def user_params
       params.require(:user).permit(:first_name, :last_name, :avatar, :role_ids => [])
    end

end

app/views/administration/check_file.html.haml
%h1 Comprobación del fichero CSV
- if @file_is_correct
  %p
    = "The file is OK, #{pluralize(@users_to_create, 'user')} will be created"
    %br
    = link_to 'Create Users!!!', administration_create_users_path, class: 'btn btn-info'
- else
  %p
    = "#{pluralize(@users_to_create, 'user')} would be created, but the file has errors:"
  %ul
  - @CSV_errors.each do |error|
    %li
      = "#{error}"
  - @data_errors.each do |error|
    %li
      = "#{error}"
  - @role_errors.each do |error|
    %li
      = "#{error}"
  %br
  - @users.each do |f|
    = "#{@f.to_s}"
  = link_to 'Back to user list', administration_list_users_path

app/views/administration/create_users.html.haml
%h1 Imported users from CSV file
%p
  =# "#{pluralize(@users_created, 'user')} created."
  = @error
  = @CSV_errors
  %br
  = link_to 'Back to user list', administration_list_users_path

app/views/administration/edit_user.html.haml
%h1 
  // = "Edit user " @user.first_name " " @user.last_name

  = simple_form_for @user, :url => url_for(:action => 'update_user', :controller => 'administration'), :method => :put do |f|
    = f.error_notification

    .form-inputs
      = f.input :first_name
      = f.input :last_name
      = f.file_field :avatar
      = f.association :roles, as: :check_boxes

    .form-actions
      = f.button :submit

app/views/administration/list_groups.html.haml
%h1 Groups
%p You can manage groups in this page

=link_to 'Add role', new_role_path, class: 'btn btn-info'
%br

%table.table.table-bordered.table-hover
  %thead
    // %th
    // Name
    = content_tag :th, sort_link(@q, :name)
    %th
      Machine Lifetime
    %th
      Machine Idletime
    %th
      Concurrent Machines
    %th 
      Actions
  %tbody
    - @groups.each do |group| 
      %tr
        %td
          =group.name
        %td
          =group.machine_lifetime
        %td
          =group.machine_idletime
        %td
          =group.concurrent_machines
        %td
          =link_to 'See users', administration_users_from_group_path(:id => group.id), :class => 'btn btn-mini btn-info', id: "see_users_from_group_#{group.id}"
          =link_to 'Edit', edit_role_path(:id => group.id), :class => 'btn btn-mini btn-info', id: "edit_role_#{group.id}"
          =link_to 'Delete', group,
            class: 'btn btn-mini btn-danger', method: :delete, data: { confirm: 'Are you sure?' }, 
            id: "delete_role_#{group.id}"

= paginate @groups



      

app/views/administration/list_users.html.haml
%h1 Users
%br

.container
  .span7
    .form-search.right
      = search_form_for @q, url: administration_list_users_path do |f| 
        .search-query
          = f.text_field :email_cont, :placeholder => "Email contains ..."
          = f.submit
  .span4
    = link_to 'Create users from CSV file', administration_upload_csv_path, class: 'btn btn-info'

%table.table.table-bordered.table-hover
  %thead
    %th
      Avatar
    = content_tag :th, sort_link(@q, :last_name)
    = content_tag :th, sort_link(@q, :first_name)
    = content_tag :th, sort_link(@q, :email)
    //%th
    //  Last Name
    //%th
    //  First Name
    //%th 
    //  Email
    %th 
      Actions
  %tbody
    - @users.each do |user| 
      - @class = nil
      - if !user.confirmed?
        - @class = "warning"
      - elsif !user.approved?
        - @class = "info"
      %tr{ :class => @class}
        %td
          %center
            = image_tag user.avatar.url(:thumb)
        %td
          =user.last_name
        %td
          =user.first_name
        %td
          =user.email
        %td
          - if user.confirmed?
            %button.btn.btn-mini.btn-success Confirmed
          - else
            %button.btn.btn-mini.btn-danger Not confirmed
          - if user.approved?
            =link_to 'Approved', administration_toggle_approved_user_path(:id => user.id), :method => :put, :class => 'btn btn-mini btn-success'
          - else
            =link_to 'Not approved', administration_toggle_approved_user_path(:id => user.id), :method => :put, :class => 'btn btn-mini btn-danger'
          =link_to 'Edit', administration_edit_user_path(id: user.id), :class => 'btn btn-mini btn-success', id: "edit_#{user.id}"
          =link_to 'Delete', administration_delete_user_path(id: user.id), 
              class: 'btn btn-mini btn-danger', method: :delete, data: { confirm: 'Are you sure?' }, 
              id: "delete_#{user.id}"

= paginate @users

      

app/views/administration/upload_csv.html.haml
%h1 Create users from CSV file
%p From this option you can upload a file with a list of the users you need to create.
%p You have to edit a file with these characteristics:
%ul
  %li The file MUST be in CSV format.
  %li No header with the names of the fields.
  %li One row per user.
  %li The format must be: "mail", "Last Name", "First Name", "role1, role2..."
%br
  
  = form_tag({action: :check_file}, multipart: true) do
    = file_field_tag 'upload'
    = submit_tag("Upload and check the file")


  

app/views/administration/users_from_group.html.haml
%h1 #{@role.name.capitalize} Users


%table.table.table-bordered.table-hover
  %thead
    %th
      Last Name
    %th
      First Name
    %th 
      Email
    %th 
      Actions
  %tbody
    - @users.each do |user| 
      - @class = nil
      - if !user.confirmed?
        - @class = "warning"
      - elsif !user.approved?
        - @class = "info"
      %tr{ :class => @class}
        %td
          =user.last_name
        %td
          =user.first_name
        %td
          =user.email
        %td
          - if user.confirmed?
            %button.btn.btn-mini.btn-success Confirmed
          - else
            %button.btn.btn-mini.btn-danger Not confirmed
          - if user.approved?
            =link_to 'Approved', administration_toggle_approved_user_path(:id => user.id), :method => :put, :class => 'btn btn-mini btn-success'
          - else
            =link_to 'Not approved', administration_toggle_approved_user_path(:id => user.id), :method => :put, :class => 'btn btn-mini btn-danger'

      