config/routes.rb
Broker::Application.routes.draw do
require 'sidekiq/web'
authenticate :user, lambda { |u| u.admin? } do
  mount Sidekiq::Web => '/sidekiq'
end

  resources :cloud_servers do
    resources :images
  end

  get "administration/list_users"
  get "administration/list_groups"
  get "administration/users_from_group"
  put "administration/toggle_approved_user"
  get 'administration/edit_user/:id', to: 'administration#edit_user', as: 'administration_edit_user'
  put 'administration/update_user/:id', to: 'administration#update_user', as: 'administration_update_user'
  delete "administration/delete_user"
  get 'administration/upload_csv'
  post 'administration/check_file'
  get 'administration/create_users'

  post 'machines/create/:id', to: 'machines#create', as: 'create_machine'
  get 'machines/:id', to: 'machines#show', as: 'machine'
  get 'machines', to: 'machines#index', as: 'machines'
  delete 'machines/:id', to: 'machines#destroy', as: 'destroy_machine'
  get 'machines/reboot/:id', to: 'machines#reboot', as: 'reboot_machine'

  resources :roles

  devise_for :users
  get "welcome/index"

  root 'welcome#index'

end

app/models/machine.rb
class Machine < ActiveRecord::Base
  belongs_to :image
  belongs_to :user

  scope :paused, ->(image) { where("image_id = ? and user_id is null", image) }

  def self.launch(image)
    # TODO: Crear usuario, clave, ip y puerto 
    clave = (0...16).map { ('a'..'z').to_a[rand(26)] }.join
    machine = Machine.new(:image => image, :remote_username => "openvdi", :remote_password => clave )
  
    ready_machine = Machine.paused(image.id).first
    return machine, ready_machine
  end

  def cloud_server
    self.image.cloud_server
  end

  def cloud_create
     self.cloud_server.create_server(:name => "openvdi" + self.id.to_s, :image => self.image.machine, :flavor => self.image.flavor, :password => self.remote_password, :network => self.image.network)
  end

  def cloud_destroy
    self.cloud_server.destroy_server("openvdi" + self.id.to_s)
  end

  def unpause
    self.cloud_server.unpause("openvdi" + self.id.to_s)
  end

  def pause
    self.cloud_server.pause("openvdi" + self.id.to_s)
  end

  def reboot
    self.cloud_server.reboot("openvdi" + self.id.to_s)
  end

  def set_ip
    puts "**************************************************"
    puts "\n\nENTRANDO EN MACHINE IP CON ID #{self.id}\n\n"
    puts "**************************************************"

    if self.remote_address
      self.remote_address
    else
      self.remote_address = self.cloud_server.set_ip("openvdi" + self.id.to_s)
      self.save
      remote_address
    end
    rescue
      puts "************************"
      puts " ERROR: IP NOT AVAILABLE" 
      puts $!, $@
      puts "************************"
      GeneralMailer.errorMail("Error Assigning IP to  Machine. Connection problems?").deliver
      ""
  end

  def ip
    if self.remote_address
      self.remote_address
    else
      ""
    end
 end

  def must_destroy?
    max_lifetime_expired || max_idletime_expired
  end

  def max_lifetime_expired
    if user 
      if user.max_lifetime == 0
        false
      else
        Time.now > updated_at.to_time + user.max_lifetime.hours
      end
    else
      false
    end
  end

  def max_idletime_expired
    if user 
      if user.max_idletime == 0
        false
      else
        Time.now > user.current_sign_in_at + user.max_idletime.hours
      end
    else
      false
    end
  end

  def self.check_expired
    Machine.all.each do |maquina|
      if maquina.must_destroy? 
        puts "Destroying Machine #{maquina.id}. Owner: #{maquina.user.email}"
        begin
          maquina.cloud_destroy
        rescue Timeout::Error || TypeError || Errno::ECONNREFUSED
          maquina.destroy
        else
          maquina.destroy
        end
      end
    end
  end
end

app/controllers/machines_controller.rb
class MachinesController < ApplicationController
  before_action :set_machine, only: [:show, :destroy, :reboot]

  def index
    @machines = Machine.all
    authorize @machines
 end

  def show
    authorize @machine
    respond_to do |format|
      format.html
    end
  end

  def create
    @fakemachine = Machine.new
    authorize @fakemachine
    @machine, @ready_machine = Machine.launch(Image.find_by_id(params.require(:id)))
    if @ready_machine 
      @ready_machine.user = current_user
      @ready_machine.save
    else 
      redirect_to root_path, notice: 'Error creating machine. Contact with Administrator'
      GeneralMailer.errorMail("Error Creating Machine. Quota problems?").deliver
      return
    end
    if @machine.save
      StartMachine.perform_async(@machine.id)
      redirect_to @ready_machine, notice: 'Machine was successfully created.' 
    else
      redirect_to root_path, notice: 'Error creating machine. Contact with Administrator'
      GeneralMailer.errorMail("Error Creating Machine. Quota problems?").deliver
    end
  end

  def destroy
    authorize @machine
    # TODO: Quitar ip flotante
    @machine.cloud_destroy
    rescue Timeout::Error => e
      @mensaje_error = "Machine has been deleted from database, but there is no connection with cloud. YOU SHOULD DELETE THIS VM MANUALLY FROM THE CLOUD. Reason: #{e}. #{@machine.cloud_server.description} - #{@machine.id}"
      @machine.destroy
      redirect_to root_path, notice: @mensaje_error 
    rescue Errno::ECONNREFUSED 
      @mensaje_error = "Machine has been deleted from database, but there is no connection with cloud. YOU SHOULD DELETE THIS VM MANUALLY FROM THE CLOUD. Reason: Connection refused. #{@machine.cloud_server.description} - #{@machine.id}"
      @machine.destroy
      redirect_to root_path, notice: @mensaje_error 
    
    rescue TypeError => e
      @mensaje_error = "Machine has been deleted from database, but there isn't a machine with id #{@machine.id} in #{@machine.cloud_server.description}"
      @machine.destroy     
      redirect_to root_path, notice: @mensaje_error
    rescue
      @mensaje_error = "  Machine has been deleted from database, but there is an error deleting  machine with id #{@machine.id} in #{@machine.cloud_server.description}. Please, do it manually"
      @machine.destroy
      redirect_to root_path, notice: @mensaje_error
    else 
     @machine.destroy 
     redirect_to root_path
    end

  def reboot
    authorize @machine
    @machine.reboot
    redirect_to root_path, notice: ' Machine has been rebooted.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_machine
      @machine = Machine.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def machine_params
      params.require(:machine).permit(:image_id, :user_id, :remote_username, :remote_password, :remote_address, :remote_port)
    end

end

app/views/machines/index.html.haml
%h1 Running machines

%table.table.table-bordered.table-hove
  %thead
    %th
    %th Image
    %th Description
    %th Name
    %th Address
    %th User
    %th Actions

  %tbody
  - @machines.each do |machine|
    %tr
      %td
        %center= image_tag machine.image.avatar.url(:thumb)
      %td= link_to machine.image.name, cloud_server_image_path(machine.image.cloud_server, machine.image)
      %td= machine.image.description
      %td= "openvdi#{machine.id}"
      %td= machine.ip
      %td= machine.user ? machine.user.email : ""
      %td 
        =link_to 'Connect', machine_path(machine) , :class => 'btn btn-mini btn-info', :id => "connect_machine_#{machine.id}", :method => :get
        =link_to 'Reboot', reboot_machine_path(machine) , :class => 'btn btn-mini btn-danger', :id => "reboot_machine_#{machine.id}", :method => :get, :data => { :confirm => 'Rebooting machine. Are you sure?' }
        =link_to 'Destroy', machine_path(machine) , :class => 'btn btn-mini btn-danger', :id => "destroy_machine_#{machine.id}", :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

app/views/machines/show.html.haml
%h1 Machine launched


= link_to "View connection parameters", "#modalparameters", :role => "button", :class => "btn btn-primary", :data =>{:toggle =>"modal"}

%div{:id =>"modalparameters", :class => "modal hide fade", :tabindex => "-1", :role => "dialog", :aria => {:labelledby => "myModalLabel", :hidden =>"true"}}
  %div{:class => "modal-header"}
    %button{:type => "button", :class =>"close", :data => {:dismiss =>"modal"}, :aria => {:hidden => "true"}}
      x
    %h4
      %center
        You can connect manually to the machine with this parameters using RDP
  %div{:class => "modal-body"}
    %p
      %b Remote username:
      = @machine.remote_username
    %p
      %b Remote password:
      = @machine.remote_password
    %p
      %b Remote address:
      = @machine.ip

%br
%br
%p
  If you don't connect automagically, do this :)
%p 
  Check 
  = link_to 'here', 'http://www.java.com/es/download/installed.jsp'
  if you have Java installed. Then, add this host to trust sites in your Java Control Panel. Security tab -> Edit Sites
%p
  If you are using Linux, install freerdp (sudo apt-get install freerdp-x11)
%p
  If you are using Mac OS X, install CoRD(http://sourceforge.net/projects/cord/files/cord/0.5.7/CoRD_0.5.7.zip/download) in your application folder.

%applet{ :code => "appletvdi.class", :archive => "/applet/appletvdi.jar" }
  %param{ :name => "vdidesktop_ip", :value => "#{@machine.ip}" }
  %param{ :name => "login", :value => "#{@machine.remote_username}" }
  %param{ :name => "password", :value => "#{@machine.remote_password}" }
  %param{ :name => "resolution", :value => "#{current_user.resolution}" }
  %param{ :name => "speed", :value => "#{current_user.speed}" }
  %param{ :name => "folder", :value => "#{current_user.folder}" }
  %param{ :name => "gatewayenabled", :value => "#{current_user.gatewayenabled}" }
  %param{ :name => "gatewayhost", :value => "#{current_user.gatewayhost}" }
  %param{ :name => "gatewayuser", :value => "#{current_user.gatewayuser}" }
  %param{ :name => "gatewaypassword", :value => "#{current_user.gatewaypassword}" }

app/views/machines/show.rdp.erb
url: <%= @machine.id %>

app/views/machines/show.vnc.erb
[Connection]
Host=kaneda.inf.um.es:5901
UserName=raul
Password=b5ddec44d7b40604
Encryption=Server
SecurityNotificationTimeout=2500
SelectDesktop=
ProxyServer=
ProxyType=
ProxyUserName=
ProxyPassword=
SingleSignOn=1
[Options]
UseLocalCursor=1
FullScreen=1
RelativePtr=0
FullColor=0
ColorLevel=pal8
PreferredEncoding=ZRLE
AutoSelect=1
Shared=1
SendPointerEvents=1
SendKeyEvents=1
ClientCutText=1
ServerCutText=1
ShareFiles=1
EnableChat=1
EnableRemotePrinting=1
ChangeServerDefaultPrinter=1
PointerEventInterval=0
PointerCornerSnapThreshold=30
Scaling=None
MenuKey=F8
EnableToolbar=1
AutoReconnect=1
ProtocolVersion=
AcceptBell=1
ScalePrintOutput=1
PasswordFile=
VerifyId=2
IdHash=
WarnUnencrypted=1
DotWhenNoCursor=1
FullScreenChangeResolution=0
UseAllMonitors=0
Emulate3=0
Emulate2=0
Monitor=-1