config/routes.rb
Broker::Application.routes.draw do
require 'sidekiq/web'
authenticate :user, lambda { |u| u.admin? } do
  mount Sidekiq::Web => '/sidekiq'
end

  resources :cloud_servers do
    resources :images
  end

  get "administration/list_users"
  get "administration/list_groups"
  get "administration/users_from_group"
  put "administration/toggle_approved_user"
  get 'administration/edit_user/:id', to: 'administration#edit_user', as: 'administration_edit_user'
  put 'administration/update_user/:id', to: 'administration#update_user', as: 'administration_update_user'
  delete "administration/delete_user"
  get 'administration/upload_csv'
  post 'administration/check_file'
  get 'administration/create_users'

  post 'machines/create/:id', to: 'machines#create', as: 'create_machine'
  get 'machines/:id', to: 'machines#show', as: 'machine'
  get 'machines', to: 'machines#index', as: 'machines'
  delete 'machines/:id', to: 'machines#destroy', as: 'destroy_machine'
  get 'machines/reboot/:id', to: 'machines#reboot', as: 'reboot_machine'

  resources :roles

  devise_for :users
  get "welcome/index"

  root 'welcome#index'

end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "StackVDI"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"


  %body

    - if current_user
      .navbar.navbar-fluid-top
        .navbar-inner
          .container-fluid
            %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
              %span.icon-bar
              %span.icon-bar
              %span.icon-bar
            %a.brand(href="/") StackVDI
            .container.nav-collapse
              - if user_signed_in?
                %ul.nav.pull-right
                  = drop_down current_user.last_name + ', ' + current_user.first_name do
                    = menu_item "Preferences", edit_user_registration_path
                    = drop_down_divider
                    = menu_item "Logout", destroy_user_session_path, :method => :delete, :id => "logout"
                  = image_tag current_user.avatar.url(:thumb), :class => "img-rounded"

    .container-fluid

    .row-fluid
    - if current_user && current_user.admin?
      .span2
        .well.sidebar-nav
          %ul.nav.nav-list
            %li.nav-header Cloud
            %li= link_to "Cloud servers", cloud_servers_path
            %li= link_to "Running Machines", machines_path
            %li.nav-header Users
            %li= link_to "Users", administration_list_users_path, :id => "userslist"
            %li= link_to "Groups", administration_list_groups_path, id: "groupslist"
      .span10
        = bootstrap_flash
        = yield
    - elsif current_user
      .container
        .span12
          = bootstrap_flash
      .container 
        .span12
          = yield
    - else 
      #home
        .container
          .span12
            %br
            = bootstrap_flash
            %br
        .container
          .span4
          .span4
            .well
              = yield
          .span4
        .container
          .span12
            %footer
              %p 
                = link_to 'StackVDI', 'http://www.stackvdi.com', :style=>'color:#EEEEEE;'
              %br
              %br
              %br
              %br
              %br
              %br
              %br
              %br
              %br
              %br
              %br
              %br
              %br
              %br
              %br